In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [5]:
dependent=dataset[['charges']]
dependent

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [7]:
X_train.values

array([[18.   , 28.215,  0.   ,  0.   ,  0.   ],
       [39.   , 32.8  ,  0.   ,  0.   ,  0.   ],
       [52.   , 46.75 ,  5.   ,  0.   ,  0.   ],
       ...,
       [40.   , 25.08 ,  0.   ,  1.   ,  0.   ],
       [19.   , 35.53 ,  0.   ,  1.   ,  0.   ],
       [33.   , 18.5  ,  1.   ,  0.   ,  0.   ]])

In [8]:
!pip install xgboost

In [9]:
import xgboost as xg
from xgboost import XGBRegressor
rgr = XGBRegressor()
from sklearn.svm import SVR
rgr= SVR(C=1.0, epsilon=0.2)

In [10]:
rgr.fit(X_train,Y_train)

C:\Users\axisi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\axisi\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.2,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [11]:
y_pred=rgr.predict(X_test)

In [12]:
y_pred

array([9581.61760687, 9570.96721563, 9575.71672976, 9582.57545454,
       9574.83632233, 9574.64346563, 9569.79526586, 9580.68128237,
       9569.08058999, 9571.02785386, 9575.02488465, 9581.60227577,
       9570.01948313, 9572.83692906, 9571.84214575, 9579.06196644,
       9581.93490536, 9571.63969713, 9567.33480331, 9570.35197114,
       9581.92578871, 9584.25617229, 9580.8654397 , 9573.20225697,
       9569.55259094, 9574.03416686, 9574.83884846, 9567.43414848,
       9568.60936037, 9571.92855036, 9571.46401833, 9577.44117239,
       9583.6742416 , 9580.14599364, 9572.81863134, 9566.65176673,
       9573.44041194, 9575.23958235, 9567.02780962, 9567.09495373,
       9574.25748836, 9568.64044158, 9572.0189405 , 9579.78722567,
       9570.60322593, 9570.81740895, 9579.39363568, 9570.95969586,
       9573.33633175, 9580.80697859, 9569.64080759, 9573.72275512,
       9575.49845866, 9579.99518181, 9577.70120875, 9575.00269885,
       9572.87941629, 9578.38703467, 9574.63444032, 9581.09970

In [13]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)

In [14]:
r_score

-0.08947360164580087

In [15]:
import pickle
filename="finalized_model_xgboost.sav"

In [16]:
pickle.dump(rgr, open(filename,"wb"))

In [17]:
loaded_model=pickle.load(open("finalized_model_xgboost.sav","rb"))
result=loaded_model.predict([[54,7,96,231,43]])

In [19]:
result

array([9575.02149231])